/** All option files that belong to the current behavior have to be included by this file. */

#include "Options/Soccer.h"

#include "Options/GameControl/HandleGameState.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
#include "Options/GameControl/ReadyState.h"
#include "Options/GameControl/Play.h"
#include "Options/GameControl/Corner.h"
#include "Options/GameControl/SideKick.h"
#include "Options/GameControl/FreeKick.h"
#include "Options/GameControl/GoalFreeKick.h"



#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/LookAtBall.h"
#include "Options/HeadControl/LookAtGlobalBall.h"
#include "Options/HeadControl/LookAtLandmark.h"
#include "Options/HeadControl/LookLeftAndRight.h"
#include "Options/HeadControl/LookRightAndLeft.h"

#include "Options/Output/Activity.h"
#include "Options/Output/Annotation.h"
#include "Options/Output/HeadControlMode.h"
#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/Output/HeadMotionRequest/SetHeadTarget.h"
#include "Options/Output/HeadMotionRequest/SetHeadTargetOnGround.h"

#include "Options/Output/MotionRequest/InWalkKick.h"
#include "Options/Output/MotionRequest/Esorcista.h"
#include "Options/Output/MotionRequest/SpecialAction.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/FightForBall.h"
#include "Options/Output/MotionRequest/WalkAtAbsoluteSpeed.h"
#include "Options/Output/MotionRequest/WalkAtRelativeSpeed.h"
#include "Options/Output/MotionRequest/WalkToTarget.h"
#include "Options/Output/MotionRequest/GetUpEngine.h"
#include "Options/Output/MotionRequest/Approacher.h"
#include "Options/Output/MotionRequest/Approacher2020.h"
#include "Options/Output/MotionRequest/Fight2020.h"
#include "Options/Output/MotionRequest/ChinaApproacher.h"
#include "Options/Output/MotionRequest/WalkWithBall.h"
#include "Options/Output/MotionRequest/GetIntoReadyPosition.h"
#include "Options/Output/MotionRequest/Kicks.h"
#include "Options/Output/MotionRequest/Cheers.h"
#include "Options/Output/MotionRequest/Move.h"
#include "Options/Output/MotionRequest/MoveWithBall.h"
#include "Options/Output/MotionRequest/PenaltyApproacher.h"
#include "Options/Output/MotionRequest/PenaltyPreApproacher.h"
#include "Options/Output/MotionRequest/SearchBallHead.h"
#include "Options/Output/MotionRequest/SPQRWalkTo.h"
#include "Options/Output/MotionRequest/StopBall.h"
#include "Options/Output/MotionRequest/Stopper.h"
#include "Options/Output/MotionRequest/Turn.h"
#include "Options/Output/MotionRequest/WalkToTargetPathPlanner.h"
#include "Options/Output/MotionRequest/RunUpWalkToTarget.h"
#include "Options/Output/MotionRequest/FreeKickDistance.h"
#include "Options/Output/MotionRequest/Dribble.h"
#include "Options/Output/MotionRequest/InWalkKickApproacher.h"
#include "Options/Output/MotionRequest/SideKicking.h"
#include "Options/Output/MotionRequest/CoverCornerKick.h"
#include "Options/Output/MotionRequest/GoBehindStriker.h"
#include "Options/Output/MotionRequest/Turn360.h"
#include "Options/Output/MotionRequest/TurnR360.h"
#include "Options/Output/MotionRequest/FastApproacher.h"
#include "Options/Output/MotionRequest/WalkQuarterCircleDownLeft.h"
#include "Options/Output/MotionRequest/WalkQuarterCircleUpLeft.h"
#include "Options/Output/MotionRequest/TrialWalk.h"
//********************TECHNICAL CHALLENGE********************
#include "Options/Output/MotionRequest/CommunicateWithGestures.h"
//#define DETECT_OBS_POSE
#ifdef DETECT_OBS_POSE
#include "Options/Roles/StrikerCornerKickChallenge.h"
#include "Options/Roles/ReceiverCornerKickChallenge.h"
#endif
//******************END TECHNICAL CHALLENGE********************

#include "Options/Output/MotionRequest/Goalie/goalieFastDiveLeft.h"
#include "Options/Output/MotionRequest/Goalie/goalieFastDiveRight.h"
#include "Options/Output/MotionRequest/Goalie/GoalieKickAway.h"




#include "Options/Output/PlaySound.h"

#include "Options/Roles/Striker.h"
#include "Options/Roles/Goalie.h"
#include "Options/Roles/Guard.h"
#include "Options/Roles/PenaltyStriker.h"
#include "Options/Roles/PlanJolly.h"
#include "Options/Roles/Searcher.h"
#include "Options/Roles/SimpleJolly.h"
#include "Options/Roles/StrikerDemo.h"
#include "Options/Roles/StrikerDev.h"
#include "Options/Roles/StupidJolly.h"
#include "Options/Roles/Supporter.h"
#include "Options/Roles/Defender.h"
#include "Options/Roles/PenaltyShooter.h"
#include "Options/Roles/StrikerCornerKick.h"
#include "Options/Roles/DefenderAU.h"
#include "Options/Roles/SupporterAU.h"
#include "Options/Roles/JollyAU.h"
#include "Options/Roles/StrikerAU.h"
#include "Options/Skills/GetUp.h"
#include "Options/Tools/ButtonPressedAndReleased.h"
#include "Options/Tools/USBCheck.h"
#include "Options/Roles/Striker2020.h"
#include "Options/Roles/StrikerAUMF.h"
#include "Options/Roles/Goalie2020.h"
#include "Options/Roles/GoalieCore.h"
